### ISSUE TITLE
Configurable Automatic Git Tag Creation

### ISSUE THREAD

**Issue by nishedcob** [ioet/release-automation#6]
Merged pull requests to configured branches should automatically create a git tag based on the bumped version (see #5).

The configuration file schema (perhaps named something like `versioning.yaml` at repository root) could look something like:
```yaml
initial version:
  patch: 0
  minor: 0
  major: 0
versioning:
  - branch: expirimental
    bump: no
    tag: no
  - branch: develop
    bump: patch
    tag: {major}.{minor}.{patch}-{commit_short_hash}
  - branch: staging
    bump: minor
    tag: {major}.{minor}.{patch}-stg
  - branch: master
    bump: no
    tag: {major}.{minor}.{patch}-rc{build_number}
  - branch: production
    bump: major
    tag: v{major}.{minor}.{patch}
```
(if no previous tags are found, treat the last known version as `v0.0.0`)
(every merge to a branch named `experimental` should not perform any version bump and merge commits should not be tagged)
(every merge to a branch named `develop` should increment the patch version, for example `v0.0.0` ->  `v0.0.1`, and merge commits should be tagged for example like `0.0.1-abc0123` where `abc0123` is the short commit hash)
(every merge to a branch named `staging` should increment the minor version, resetting the patch as per #5, for example `v0.0.0` -> `v0.1.0` or `v0.1.1` -> `v0.2.0`, and merged commits should be tagged for example like `0.1.0-stg` or `0.2.0-stg`)
(every merge to a branch named `master` should increment only the `master` branch build number which should reset whenever the major/minor/patch number changes, for example, the tagging policy would look something like `v0.0.0` [input version] -> `0.0.0-rc1` -> `0.0.0-rc2`)
(every merge to a branch named `production` should increment the major version, reseting the minor and patch versions as per #5, for example: `v0.0.0` -> `v1.0.0`, `v1.0.1` -> `v2.0.0`, `v2.1.3` -> `v3.0.0` and the `production` branch should be tagged in the format of `v1.0.0`, `v2.0.0`, `v3.0.0`, etc)

Another potential configuration file schema might look something like:
```yaml
initial version:
  patch: 1
  minor: 0
  major: 0
versioning:
  - branch: develop
    bump: annotation
    bump_annotation:
      patch: (patch)
      minor: (minor)
      major: no
    tag: {major}.{minor}.{patch}-{commit_short_hash}
  - branch: staging
    bump: no
    tag: {major}.{minor}.{patch}-stg
  - branch: master
    bump: no
    tag: {major}.{minor}.{patch}-rc{build_number}
  - branch: production
    bump: no
    tag: v{major}.{minor}.{patch}
```
(if no previous tags are found, treat the last known version as `v1.0.0`)
(every merge to a branch named `experimental` should not perform any version bump and merge commits should not be tagged)
(every merge to a branch named `develop` should increment the highest annotation type based on the PR title, with permitted annotations being: `(patch)` `<` `(minor)` with no annotation being available for major bumps)
(every merge to a branch named `staging` should not change the version)
(every merge to a branch named `master` should not change the version)
(every merge to a branch named `production` should not change the version)
(tagging on all branches follows the example set previously)

This should be implemented together with #5.
